// <auto-generated />
using System;
using Mde.Project.Mobile.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mde.Project.Mobile.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517131135_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MemoriaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId");

                    b.ToTable("MediaItems");
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.Memoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Occation")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Memorias");
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("Mde.Project.Mobile.Core.Entities.Memoria", "Memoria")
                        .WithMany("MediaMaterial")
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.Memoria", b =>
                {
                    b.HasOne("Mde.Project.Mobile.Core.Entities.Address", "MemoriaAddress")
                        .WithOne("Memoria")
                        .HasForeignKey("Mde.Project.Mobile.Core.Entities.Memoria", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoriaAddress");
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.Address", b =>
                {
                    b.Navigation("Memoria")
                        .IsRequired();
                });

            modelBuilder.Entity("Mde.Project.Mobile.Core.Entities.Memoria", b =>
                {
                    b.Navigation("MediaMaterial");
                });
#pragma warning restore 612, 618
        }
    }
}
