// <auto-generated />
using System;
using Mde.SourceOfTruth.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mde.SourceOfTruth.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515184332_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("MemoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Paris",
                            Country = "France",
                            HouseNumber = "5",
                            Latitude = 48.858370100000002,
                            Longitude = 2.2944813000000002,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Street = "Champ de Mars"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            City = "Rome",
                            Country = "Italy",
                            HouseNumber = "1",
                            Latitude = 41.890210199999999,
                            Longitude = 12.492230899999999,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Street = "Piazza del Colosseo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            City = "Berlin",
                            Country = "Germany",
                            HouseNumber = "1",
                            Latitude = 52.516274600000003,
                            Longitude = 13.377704100000001,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Street = "Pariser Platz"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            City = "Barcelona",
                            Country = "Spain",
                            HouseNumber = "401",
                            Latitude = 41.403629899999999,
                            Longitude = 2.1743557999999998,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Street = "Carrer de Mallorca"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            City = "London",
                            Country = "United Kingdom",
                            HouseNumber = "1",
                            Latitude = 51.500729200000002,
                            Longitude = -0.1246254,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Street = "Westminster"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            City = "Athens",
                            Country = "Greece",
                            HouseNumber = "1",
                            Latitude = 37.971532000000003,
                            Longitude = 23.725749,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Street = "Acropolis Hill"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            City = "New York",
                            Country = "USA",
                            HouseNumber = "1",
                            Latitude = 40.689249400000001,
                            Longitude = -74.044500400000004,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000007"),
                            Street = "Liberty Island"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            City = "Rio de Janeiro",
                            Country = "Brazil",
                            HouseNumber = "1",
                            Latitude = -22.951916000000001,
                            Longitude = -43.210487000000001,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000008"),
                            Street = "Parque Nacional da Tijuca"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            City = "Agra",
                            Country = "India",
                            HouseNumber = "1",
                            Latitude = 27.175144800000002,
                            Longitude = 78.042142200000001,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000009"),
                            Street = "Dharmapuri"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            City = "Sydney",
                            Country = "Australia",
                            HouseNumber = "1",
                            Latitude = -33.856784400000002,
                            Longitude = 151.21529670000001,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000010"),
                            Street = "Bennelong Point"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            City = "Fujinomiya",
                            Country = "Japan",
                            HouseNumber = "1",
                            Latitude = 35.360625499999998,
                            Longitude = 138.7273634,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000011"),
                            Street = "Kitayama"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            City = "Niagara Falls",
                            Country = "Canada",
                            HouseNumber = "1",
                            Latitude = 43.079900000000002,
                            Longitude = -79.074700000000007,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000012"),
                            Street = "Niagara Parkway"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            City = "Grand Canyon Village",
                            Country = "USA",
                            HouseNumber = "1",
                            Latitude = 36.106965199999998,
                            Longitude = -112.1129972,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000013"),
                            Street = "Grand Canyon Village"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            City = "Dubai",
                            Country = "UAE",
                            HouseNumber = "1",
                            Latitude = 25.197196999999999,
                            Longitude = 55.274375999999997,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000014"),
                            Street = "1 Sheikh Mohammed bin Rashid Blvd"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            City = "Beijing",
                            Country = "China",
                            HouseNumber = "1",
                            Latitude = 40.431907699999996,
                            Longitude = 116.5703749,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000015"),
                            Street = "Badaling"
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222220"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/france.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/frankrijk.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/athens.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000006"),
                            Type = "Photo"
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Memoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Memorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iconische toren en symbool van Parijs.",
                            EventDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eiffel Tower",
                            Occation = "Reis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oud Romeins amfitheater.",
                            EventDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colosseum",
                            Occation = "Reis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historische stadspoort in Berlijn.",
                            EventDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brandenburg Gate",
                            Occation = "Werk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beroemde basiliek ontworpen door Gaudí.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sagrada Familia",
                            Occation = "Reis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bekende klokkentoren van Londen.",
                            EventDate = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Big Ben",
                            Occation = "Ander"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oude citadel met historische tempels.",
                            EventDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acropolis",
                            Occation = "Uitgaan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vrijheidsbeeld in New York.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Statue of Liberty",
                            Occation = "Uitgaan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Groot Christusbeeld op de Corcovado.",
                            EventDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christ the Redeemer",
                            Occation = "Werk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wit marmeren mausoleum.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taj Mahal",
                            Occation = "Reis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iconisch operagebouw.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sydney Opera House",
                            Occation = "Ander"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bekende vulkaan en berg.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mount Fuji",
                            Occation = "Werk"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Indrukwekkende watervallen.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Niagara Falls",
                            Occation = "Reis"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diepe kloof gevormd door de Colorado rivier.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grand Canyon",
                            Occation = "Ander"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hoogste gebouw ter wereld.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Burj Khalifa",
                            Occation = "Uitgaan"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CreatedOn = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historische verdedigingsmuur.",
                            EventDate = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Great Wall",
                            Occation = "Ander"
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Address", b =>
                {
                    b.HasOne("Mde.SourceOfTruth.Core.Entities.Memoria", "Memoria")
                        .WithOne("MemoriaAddress")
                        .HasForeignKey("Mde.SourceOfTruth.Core.Entities.Address", "MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("Mde.SourceOfTruth.Core.Entities.Memoria", "Memoria")
                        .WithMany("MediaMaterial")
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Memoria", b =>
                {
                    b.Navigation("MediaMaterial");

                    b.Navigation("MemoriaAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
