// <auto-generated />
using System;
using Mde.SourceOfTruth.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mde.SourceOfTruth.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528173130_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<Guid>("MemoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId")
                        .IsUnique();

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            City = "Paris",
                            Country = "France",
                            HouseNumber = "5",
                            Latitude = 48.858370100000002,
                            Longitude = 2.2944813000000002,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Street = "Champ de Mars"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            City = "Rome",
                            Country = "Italy",
                            HouseNumber = "1",
                            Latitude = 41.890210199999999,
                            Longitude = 12.492230899999999,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Street = "Piazza del Colosseo"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            City = "Berlin",
                            Country = "Germany",
                            HouseNumber = "1",
                            Latitude = 52.516274600000003,
                            Longitude = 13.377704100000001,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Street = "Pariser Platz"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            City = "Barcelona",
                            Country = "Spain",
                            HouseNumber = "401",
                            Latitude = 41.403629899999999,
                            Longitude = 2.1743557999999998,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Street = "Carrer de Mallorca"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            City = "London",
                            Country = "United Kingdom",
                            HouseNumber = "1",
                            Latitude = 51.500729200000002,
                            Longitude = -0.1246254,
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000005"),
                            Street = "Westminster"
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.MediaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MemoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MemoriaId");

                    b.ToTable("MediaItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris1.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris2.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris3.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222224"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris4.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222225"),
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris5.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222226"),
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris6.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222227"),
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris7.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222228"),
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/paris8.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222229"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/rome1.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222230"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/rome2.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222231"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/ventie1.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222232"),
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie2.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222233"),
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie3.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222234"),
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie4.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222235"),
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie5.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222236"),
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie6.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222237"),
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie7.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222238"),
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/venetie8.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000003"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222239"),
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/sagrada1.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Type = "Photo"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222240"),
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FilePath = "https://06dfrpsm-44338.brs.devtunnels.ms/img/sagrada2.jpg",
                            MemoriaId = new Guid("00000000-0000-0000-0000-000000000004"),
                            Type = "Photo"
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Memoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEditedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Occation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegisteredDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredDeviceId");

                    b.ToTable("Memorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedOn = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Iconische toren en symbool van Parijs.",
                            EventDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eiffel Tower",
                            Occation = "Travel",
                            RegisteredDeviceId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedOn = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oud Romeins amfitheater.",
                            EventDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Colosseum",
                            Occation = "Travel",
                            RegisteredDeviceId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CreatedOn = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Historische stadspoort in Berlijn.",
                            EventDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brandenburg Gate",
                            Occation = "Work",
                            RegisteredDeviceId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CreatedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Beroemde basiliek ontworpen door Gaudí.",
                            EventDate = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sagrada Familia",
                            Occation = "Travel",
                            RegisteredDeviceId = new Guid("99999999-9999-9999-9999-999999999999")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CreatedOn = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bekende klokkentoren van Londen.",
                            EventDate = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastEditedOn = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Big Ben",
                            Occation = "Other",
                            RegisteredDeviceId = new Guid("99999999-9999-9999-9999-999999999999")
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.RegisteredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegisteredDevices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            DeviceId = "sdfqsdg",
                            DeviceName = "A54 van Nick",
                            IsActive = true,
                            Platform = "Android",
                            RegisteredAt = new DateTime(2023, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999998"),
                            DeviceId = "PFKZOFK94839",
                            DeviceName = "Iemand anders",
                            IsActive = false,
                            Platform = "IPhone",
                            RegisteredAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Address", b =>
                {
                    b.HasOne("Mde.SourceOfTruth.Core.Entities.Memoria", "Memoria")
                        .WithOne("MemoriaAddress")
                        .HasForeignKey("Mde.SourceOfTruth.Core.Entities.Address", "MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.MediaItem", b =>
                {
                    b.HasOne("Mde.SourceOfTruth.Core.Entities.Memoria", "Memoria")
                        .WithMany("MediaMaterial")
                        .HasForeignKey("MemoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memoria");
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Memoria", b =>
                {
                    b.HasOne("Mde.SourceOfTruth.Core.Entities.RegisteredDevice", "Device")
                        .WithMany("memorias")
                        .HasForeignKey("RegisteredDeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.Memoria", b =>
                {
                    b.Navigation("MediaMaterial");

                    b.Navigation("MemoriaAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Mde.SourceOfTruth.Core.Entities.RegisteredDevice", b =>
                {
                    b.Navigation("memorias");
                });
#pragma warning restore 612, 618
        }
    }
}
